Update installation of HNPWA-vanilla documentation
cristianbote/hnpwa-vanilla pull request #11
Opened 2018-02-10 07:31 UTC by satyakresna

Hi Cristian, I just try update installation of HNPWA-vanilla documentation. You can try in local. If it runs well, please let me know. Thanks a lot.

2018-02-12 06:46 UTC, cristianbote commented
Hey @satyakresna,

Thank you! 😄 This clears up the confusing parts of running it locally, for sure. I need to check something first, because I think you can do it via `firebase-cli` and don't need to have the `python` installed.

I'll get back to you.
Thanks again!

2018-02-12 08:23 UTC, satyakresna commented
You're welcome Cristian. Nice to help the author and me how it works.

On Feb 12, 2018 2:46 PM, "Cristian Bote" <notifications@github.com> wrote:

> Hey @satyakresna <https://github.com/satyakresna>,
>
> Thank you! 😄 This clears up the confusing parts of running it locally,
> for sure. I need to check something first, because I think you can do it
> via firebase-cli and don't need to have the python installed.
>
> I'll get back to you.
> Thanks again!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cristianbote/hnpwa-vanilla/pull/11#issuecomment-364839779>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKlcMvBgKOxk25sRTtLIKTfVZOpcYryzks5tT95BgaJpZM4SA1x2>
> .
>

2018-03-01 22:27 UTC, cristianbote commented
Hey @satyakresna, I just did a commit and added the `npm run serve` command. Would you be willing to update the wording on it? I'm gonna add some comments.

2018-03-01 22:29 UTC, cristianbote requested changes
Looking forward you to your reply.

2018-03-01 22:29 UTC, cristianbote commented on README.md
> +    * `npm run build-sw`
Instead of these lines, we could run the `npm run build-prod` and end up in the same place.

2018-03-01 22:29 UTC, cristianbote commented on README.md
> +1. It will generate a `public` folder with assets (html, css, js) inside them. Move to `public` folder and run `python -m SimpleHTTPServer 8080`.
This is no longer needed, you can run `npm run serve` and would spun up a firebase locally served server.

2018-03-02 00:20 UTC, satyakresna commented
Hi @cristianbote , just finished based on your request. Done, feel free to check. Thanks a lot.

2018-03-02 09:21 UTC, cristianbote approved these changes

2018-03-02 09:22 UTC, cristianbote commented
Awesome @satyakresna!

2018-03-02 09:22 UTC, merged